### ISSUE TITLE
test: 서버 부하테스트

### ISSUE THREAD

**Issue by lybell-art** [boostcampwm-2022/Web10-MonumentGallery#194]
## Context
현재 서버에서 Notion 데이터를 기반으로 맵을 생성하는 부분은 약 20~40초로 많은 최적화가 이루어지긴 했으나, 외부 서비스를 기반으로 얼마나 많은 사용자의 요청을 버틸 수 있을지는 미지수임. 특히 CPU단에서 Notion 데이터를 후가공하고 있으므로, Node.js 서버가 아직 처리중일 때 다른 사람의 요청을 받을 수 있을지를 테스트해야 함.
## 목표
- 많은 동시요청이 일어나지 않을 미디어아트 프로젝트임을 고려, 최대 100명까지 버티면 성공으로 판정
- 혹시 다른 의견 있으면 자유롭게 수정 가능합니다

**Comment by Lipeya** [comment]
두..렵다!

**Comment by Lipeya** [comment]
현재까지의 결론: 서버가 터지기전에 notion api 사용제한이 먼저..
