### ISSUE TITLE
fix: 뒤로가기 시 메인 화면이 모뉴먼트 목록을 가져오지 못하는 버그 수정

### ISSUE THREAD

**Issue by lybell-art** [boostcampwm-2022/Web10-MonumentGallery#199]
## Context
현재 모뉴먼트 목록은 쿠키에 지금까지 불러온 데이터 자체를 저장하고 있는데, 그것 때문인지 뒤로가기 시에는 쿠키가 초기화되지 않아 데이터가 불러와지지 않는 버그가 있었음. 추가적으로 메인 화면 이동 후 삭제 로직으로 인해 중복된 데이터를 가져오는 오류도 있었음. 
## Todo
- 모뉴먼트 목록 불러오기 방식을 body나 header 방식으로 변경
- 클라이언트에서 searchState를 저장하고 헤더 or body에 담아서 요청

**Comment by Lipeya** [comment]
👍
